In [1]:
import pandas as pd

In [12]:
data = {'Name': ['John', 'Mary', 'Bob', 'Sarah', 'Tom', 'Lisa'],
        'Department': ['IT', 'Marketing', 'Sales', 'IT', 'Finance', 'Marketing'],
        'Age': [30, 40, 25, 35, 45, 28],
        'Gender': ['Male', 'Female', 'Male', 'Female', 'Male', 'Female'],
        'Salary': [50000, 60000, 45000, 55000, 70000, 55000],
        'Experience': [3, 7, 2, 5, 10, 4]}

employee_df = pd.DataFrame(data)
employee_df

    Name Department  Age  Gender  Salary  Experience
0   John         IT   30    Male   50000           3
1   Mary  Marketing   40  Female   60000           7
2    Bob      Sales   25    Male   45000           2
3  Sarah         IT   35  Female   55000           5
4    Tom    Finance   45    Male   70000          10
5   Lisa  Marketing   28  Female   55000           4

1. use **iloc** to select the first three rows

In [13]:
employee_df.iloc[:3]

   Name Department  Age  Gender  Salary  Experience
0  John         IT   30    Male   50000           3
1  Mary  Marketing   40  Female   60000           7
2   Bob      Sales   25    Male   45000           2


2. Use **loc** to select all row where Department is *Marketing*

In [14]:
employee_df.index = employee_df['Department']
employee_df.loc['Marketing']

            Name Department  Age  Gender  Salary  Experience
Department
Marketing   Mary  Marketing   40  Female   60000           7
Marketing   Lisa  Marketing   28  Female   55000           4


3. Use **iloc** to select the Age and Gender columns for the first 4 rows

In [15]:
employee_df.index = range(employee_df.shape[0])
employee_df[['Age', 'Gender']].iloc[:4]

   Age  Gender
0   30    Male
1   40  Female
2   25    Male
3   35  Female

4. Use **iloc** to select the Salary and Experience columns where Gender is 'Male'

In [16]:
employee_df.index = employee_df['Gender']
employee_df[['Salary', 'Experience']].loc['Male']

        Salary  Experience
Gender
Male     50000           3
Male     45000           2
Male     70000          10